### PR TITLE
update tutorial to DataFrames.jl 0.22.0

### PR DESCRIPTION
**Pull request by bkamins**
@logankilpatrick - you might want to have a look before I record the videos. This PR should be merged when the videos are uploaded to YouTube and links updated in JuliaAcademy.

### CODE REVIEW

**Review by logankilpatrick — APPROVED** [review]
This looks good from my first quick pass.

**Comment by logankilpatrick** [comment]
@bkamins can you check the comments on the Julia Academy site for your course to make sure there's nothing else that needs to be addressed while updating the rest of the materials?

**Comment by bkamins** [comment]
Minor things:
1. `ł` and `ń` are not typeset correctly with the font used in my name. Probably it is not possible to change it so maybe just change it to `Bogumil Kaminski` (in two places)
2. For "Next steps" (last) I would add `6.` as a prefix

Thank you

**Comment by bkamins** [comment]
@logankilpatrick - I have shared video recordings with you over Slack. Please merge this PR when the videos are uploaded

**Comment by bkamins** [comment]
@logankilpatrick - what is the status of the YouTube uploads? Thank you!

**Comment by logankilpatrick** [comment]
I have to had a chance yet but will before the end of this week

**Review by octobuss — APPROVED** [review]

**Review by octobuss — APPROVED** [review]

**Review by octobuss — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
